# Generated by Django 4.1.3 on 2022-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('geoname_id', models.BigIntegerField()),
                ('latitiude', models.FloatField()),
                ('longitiude', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
